; replace C-h with backspace
(global-set-key "\C-h" `delete-backward-char)
; not create backup(foo.txt~)
(setq make-backup-files nil)
; not create backup("#foo.txt#")
(setq auto-save-default nil)
; replace C-c with kill-ring-save(copy)
(defun wsl-copy (start end)
  (interactive "r")
  (shell-command-on-region start end "clip.exe")
  (deactivate-mark))
;(global-set-key "\C-c" `kill-ring-save)
(global-set-key "\C-c" `wsl-copy)
; replace C-x x with kill-region(cut)
(defun wsl-cut (start end)
  (interactive "r")
  (shell-command-on-region start end "clip.exe")
  (kill-region start end))
(global-set-key "\C-x\C-x" `wsl-cut)
; replace C-f C-f with isearch-forward(search)
(global-set-key "\C-x\C-f" `isearch-forward)
; replace C-s with save-buffer
(global-set-key "\C-s" `save-buffer)
; set window move
(global-set-key (kbd "C-<left>")  'windmove-left)
(global-set-key (kbd "C-<down>")  'windmove-down)
(global-set-key (kbd "C-<up>")    'windmove-up)
(global-set-key (kbd "C-<right>") 'windmove-right)
; kill windows
(global-set-key (kbd "C-w") 'delete-window)
